### ISSUE TITLE
Writing code to files?

### ISSUE THREAD

**Issue by eashanhatti** [divipp/x86-64#16]
I am writing a compiler and planned to use this library for codegen, but I can't figure out how to write generated assembly to files. Does this library not have this feature? If that's the case, how could it be implemented?

**Comment by divipp** [comment]
It is not possible to generate executables with this library.
If you want to generate executables for Linux (for example), search for minimal ELF executables for inspiration. A 120 bytes prefix may be enough if you use syscalls for communication.
